import { CurriculumTopic } from '@/types/curriculum';

export const geometryTopics: CurriculumTopic[] = [
  {
    id: 'area-perimeter',
    subject: 'geometry',
    title: 'Area & Perimeter',
    description: 'Measure and compute the size of 2D shapes — how much fence you need and how much space you have.',
    grades: [6],
    standards: ['CCSS.MATH.6.G.A.1'],
    icon: '▭',
    color: 'amber',
    prerequisiteTopicIds: [],
    lessons: [
      {
        id: 'area-perimeter-rectangles',
        topicId: 'area-perimeter',
        title: 'Rectangles',
        estimatedMinutes: 12,
        narrative: {
          setting: 'You are designing a skate park for your city. The city council needs two numbers before they can approve your plan: how much fence to buy and how much concrete to pour.',
          character: 'Maya the Park Designer',
          problemStatement: 'Design a rectangular skate park. Find its perimeter (fence needed) and area (concrete needed).',
          realWorldConnection: 'Architects, landscapers, and builders calculate area and perimeter every day to estimate materials and cost.',
        },
        phases: [
          {
            phase: 'concrete',
            instructionText: 'Drag the corners of the skate park to size it how you like. Each square on the grid = 1 meter. Count how many meters of fence you would need to go all the way around.',
            canvasComponent: 'RectangleCanvas',
            canvasInitialState: { width: 4, height: 3 },
            formativeCheck: {
              prompt: 'How many meters of fence does your park need? (Count all 4 sides)',
              type: 'numeric',
              tolerance: 10,
            },
            hint: 'Walk around the outside of the park — count every edge.',
          },
          {
            phase: 'visual',
            instructionText: 'Now watch what happens to the fence and concrete numbers as you resize the park. Can you spot a pattern in how the numbers change?',
            canvasComponent: 'RectangleCanvas',
            canvasInitialState: { width: 4, height: 3 },
            formativeCheck: {
              prompt: 'If length = 6m and width = 4m, what is the perimeter?',
              type: 'numeric',
              correctAnswer: 20,
              tolerance: 5,
            },
            hint: 'You need to add all 4 sides. Two sides have the same length. Two sides have the same width.',
          },
          {
            phase: 'abstract',
            instructionText: 'The pattern you found has a name: P = 2l + 2w and A = l × w. Type any length and width — the formula fills in automatically.',
            canvasComponent: 'RectangleCanvas',
            canvasInitialState: { width: 5, height: 4 },
            formativeCheck: {
              prompt: 'A garden is 8m long and 3m wide. A bag of fertilizer covers 6 m². How many bags do you need?',
              type: 'numeric',
              correctAnswer: 4,
              tolerance: 0,
            },
            hint: 'First find the area of the garden. Then divide by how much one bag covers.',
          },
        ],
      },
      {
        id: 'area-perimeter-composite',
        topicId: 'area-perimeter',
        title: 'Composite Shapes',
        estimatedMinutes: 15,
        narrative: {
          setting: 'The skate park is getting an upgrade — an L-shaped section for advanced skaters is being added.',
          problemStatement: 'Find the area and perimeter of L-shaped and other composite figures by breaking them into rectangles.',
          realWorldConnection: 'Most real floors, rooms, and plots of land are not perfect rectangles. Builders split them into simpler parts.',
        },
        phases: [
          {
            phase: 'concrete',
            instructionText: 'Drag the dividing line to split the L-shape into two rectangles. Count the grid squares in each piece.',
            canvasComponent: 'CompositeShapeCanvas',
            canvasInitialState: { shape: 'L', splitAt: 3 },
            formativeCheck: {
              prompt: 'What is the total area of the L-shape? (Add both pieces)',
              type: 'numeric',
              tolerance: 10,
            },
          },
          {
            phase: 'visual',
            instructionText: 'Watch the two rectangles highlight as you move the split. Their individual areas and the total update live.',
            canvasComponent: 'CompositeShapeCanvas',
            canvasInitialState: { shape: 'L', splitAt: 3 },
            formativeCheck: {
              prompt: 'If the two pieces have areas 12 m² and 8 m², what is the total area?',
              type: 'numeric',
              correctAnswer: 20,
              tolerance: 0,
            },
          },
          {
            phase: 'abstract',
            instructionText: 'A = A₁ + A₂. Composite area = sum of its parts.',
            canvasComponent: 'CompositeShapeCanvas',
            canvasInitialState: { shape: 'L', splitAt: 3 },
            formativeCheck: {
              prompt: 'An L-shaped room is made of a 5×4 rectangle and a 3×2 rectangle. What is the total area?',
              type: 'numeric',
              correctAnswer: 26,
              tolerance: 0,
            },
          },
        ],
      },
    ],
  },
  {
    id: 'angles',
    subject: 'geometry',
    title: 'Angles',
    description: 'Measure, classify, and find missing angles using angle relationships.',
    grades: [6, 7],
    standards: ['CCSS.MATH.7.G.B.5'],
    icon: '∠',
    color: 'amber',
    prerequisiteTopicIds: [],
    lessons: [
      {
        id: 'angles-types',
        topicId: 'angles',
        title: 'Types of Angles',
        estimatedMinutes: 10,
        narrative: {
          setting: 'You are a drone photographer planning camera angles for a film shoot.',
          problemStatement: 'Identify and measure acute, right, obtuse, and straight angles.',
          realWorldConnection: 'Cameras, telescopes, solar panels, and satellite dishes are all positioned using precise angle measurements.',
        },
        phases: [
          {
            phase: 'concrete',
            instructionText: 'Drag the arm of the angle to rotate it. Notice how the shape changes as you cross 90° and 180°.',
            canvasComponent: 'AngleCanvas',
            canvasInitialState: { angleDeg: 45 },
            formativeCheck: {
              prompt: 'Set the angle to exactly 90°. What is it called?',
              type: 'multiple-choice',
              choices: [
                { label: 'Acute', correct: false },
                { label: 'Right', correct: true },
                { label: 'Obtuse', correct: false },
                { label: 'Straight', correct: false },
              ],
            },
          },
          {
            phase: 'visual',
            instructionText: 'The protractor overlay shows exact degrees. Try to match the target angles shown.',
            canvasComponent: 'AngleCanvas',
            canvasInitialState: { angleDeg: 45, showProtractor: true },
            formativeCheck: {
              prompt: 'Is 135° an acute, right, or obtuse angle?',
              type: 'multiple-choice',
              choices: [
                { label: 'Acute (less than 90°)', correct: false },
                { label: 'Right (exactly 90°)', correct: false },
                { label: 'Obtuse (between 90° and 180°)', correct: true },
              ],
            },
          },
          {
            phase: 'abstract',
            instructionText: 'Complementary angles add to 90°. Supplementary angles add to 180°.',
            canvasComponent: 'AngleCanvas',
            canvasInitialState: { angleDeg: 55, showProtractor: true, showComplement: true },
            formativeCheck: {
              prompt: 'Angle A = 65°. A and B are supplementary. What is angle B?',
              type: 'numeric',
              correctAnswer: 115,
              tolerance: 0,
            },
          },
        ],
      },
    ],
  },
  {
    id: 'transformations',
    subject: 'geometry',
    title: 'Transformations',
    description: 'Translate, rotate, reflect, and dilate shapes on a coordinate plane.',
    grades: [7, 8],
    standards: ['CCSS.MATH.8.G.A.1', 'CCSS.MATH.8.G.A.2', 'CCSS.MATH.8.G.A.3'],
    icon: '⟳',
    color: 'amber',
    prerequisiteTopicIds: ['area-perimeter'],
    lessons: [
      {
        id: 'transformations-translation',
        topicId: 'transformations',
        title: 'Translation (Sliding)',
        estimatedMinutes: 12,
        narrative: {
          setting: 'You are animating a video game character. Movement on screen is a translation.',
          problemStatement: 'Translate shapes on a coordinate grid using vectors.',
          realWorldConnection: 'Every pixel movement in a video game, animation, or map navigation uses translation math.',
        },
        phases: [
          {
            phase: 'concrete',
            instructionText: 'Drag the character to move it across the grid. Count how many squares right and how many squares up you moved it.',
            canvasComponent: 'TransformCanvas',
            canvasInitialState: { mode: 'translation', shape: 'arrow', tx: 0, ty: 0 },
            formativeCheck: {
              prompt: 'You moved the character 3 squares right and 2 squares up. What is the translation vector?',
              type: 'multiple-choice',
              choices: [
                { label: '(2, 3)', correct: false },
                { label: '(3, 2)', correct: true },
                { label: '(3, -2)', correct: false },
              ],
            },
          },
          {
            phase: 'visual',
            instructionText: 'The original position (ghost) and new position both show. The arrow shows the vector (how far and in which direction).',
            canvasComponent: 'TransformCanvas',
            canvasInitialState: { mode: 'translation', shape: 'arrow', tx: 3, ty: 2, showGhost: true, showVector: true },
            formativeCheck: {
              prompt: 'Point A is at (1, 2). It is translated by vector (4, -1). Where does it end up?',
              type: 'multiple-choice',
              choices: [
                { label: '(5, 1)', correct: true },
                { label: '(5, 3)', correct: false },
                { label: '(3, 3)', correct: false },
              ],
            },
          },
          {
            phase: 'abstract',
            instructionText: "Translation rule: (x, y) → (x + a, y + b) where (a, b) is the vector.",
            canvasComponent: 'TransformCanvas',
            canvasInitialState: { mode: 'translation', shape: 'triangle', tx: 0, ty: 0, showFormula: true },
            formativeCheck: {
              prompt: 'Triangle has vertices at (0,0), (2,0), (1,2). After translation (3, -4), what are the new vertices?',
              type: 'multiple-choice',
              choices: [
                { label: '(3,-4), (5,-4), (4,-2)', correct: true },
                { label: '(3,4), (5,4), (4,6)', correct: false },
                { label: '(0,3), (2,3), (1,5)', correct: false },
              ],
            },
          },
        ],
      },
    ],
  },
  {
    id: 'pythagorean-theorem',
    subject: 'geometry',
    title: 'Pythagorean Theorem',
    description: 'Discover why a² + b² = c² and use it to find missing side lengths.',
    grades: [8],
    standards: ['CCSS.MATH.8.G.B.7', 'CCSS.MATH.8.G.B.8'],
    icon: '△',
    color: 'amber',
    prerequisiteTopicIds: ['area-perimeter'],
    lessons: [
      {
        id: 'pythagorean-proof',
        topicId: 'pythagorean-theorem',
        title: 'Why a² + b² = c²',
        estimatedMinutes: 15,
        narrative: {
          setting: 'A rescue team needs to reach a stranded hiker. There is a direct diagonal path through a flooded field — but how long is it?',
          problemStatement: 'Discover the Pythagorean theorem by visualizing squares on each side of a right triangle.',
          realWorldConnection: 'GPS, construction, navigation, and computer graphics all rely on the Pythagorean theorem hundreds of times per second.',
        },
        phases: [
          {
            phase: 'concrete',
            instructionText: 'Drag the legs of the right triangle. Count the squares in each colored square (one on each side). What do you notice?',
            canvasComponent: 'PythagoreanCanvas',
            canvasInitialState: { a: 3, b: 4, showSquares: true },
            formativeCheck: {
              prompt: 'For a triangle with legs 3 and 4: how many squares are on the longest side (hypotenuse)?',
              type: 'numeric',
              correctAnswer: 25,
              tolerance: 0,
            },
            hint: 'Count the orange squares. How does that number relate to the 9 red squares and 16 blue squares?',
          },
          {
            phase: 'visual',
            instructionText: 'Watch: the area of the square on leg a + area of square on leg b = area of square on the hypotenuse. Every time.',
            canvasComponent: 'PythagoreanCanvas',
            canvasInitialState: { a: 3, b: 4, showSquares: true, showLabels: true },
            formativeCheck: {
              prompt: 'Legs are 5 and 12. What is the area of the square on the hypotenuse?',
              type: 'numeric',
              correctAnswer: 169,
              tolerance: 0,
            },
          },
          {
            phase: 'abstract',
            instructionText: 'a² + b² = c². Enter any two sides — the third is calculated.',
            canvasComponent: 'PythagoreanCanvas',
            canvasInitialState: { a: 6, b: 8, showFormula: true },
            formativeCheck: {
              prompt: 'A ladder leans against a wall. The ladder is 10m long. Its base is 6m from the wall. How high does it reach?',
              type: 'numeric',
              correctAnswer: 8,
              tolerance: 5,
            },
          },
        ],
      },
    ],
  },
];
